url: https://support.joystick.tv
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-algolia

algolia:
  application_id: 'YXM67SR4Z2'
  index_name: joystick_support

# Site Layout Data
header:
  nav:
    - text: API
      url: '/developer_support'
    - text: Affiliates
      url: '/affiliate_support'
    - text: Contact Us
      url: '/contact_us'
sidebar:
  resources:
    - url: /faq
      text: FAQ
    - url: https://joystick.tv/terms
      text: Terms &amp; Conditions
    - url: https://joystick.tv/community-guidelines
      text: Community Guidelines
    - url: https://joystick.tv/trademark-policy
      text: Trademark Policy
    - url: https://joystick.tv/privacy
      text: Privacy Policy
    - url: https://joystick.tv/law-enforcement
      text: Law Enforcement
    - url: https://joystick.tv/dmca
      text: DCMA
    - url: https://joystick.tv/2257
      text: 18 U.S.C. ยง 2257
footer:
  social_list:
    - network_name: github
      profile_url: 'https://github.com/joysticktv'
    - network_name: bluesky
      profile_url: 'https://bsky.app/profile/joystick.tv'
    - network_name: twitter
      profile_url: 'https://twitter.com/Joystickxxx'
    - network_name: discord
      profile_url: 'https://discord.gg/zKvCf8hrGP'

# SASS settings
sass:
  sass_dir: ./theme/_sass
  style: :compressed

# Jekyll settings
layouts_dir: ./theme/_layouts
includes_dir: ./theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
